include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: ignore

linter:
  rules:
    curly_braces_in_flow_control_structures: true
    prefer_const_constructors: false
